# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: relatorio.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'relatorio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frelatorio.proto\x12\trelatorio\"\x07\n\x05Vazio\"@\n\x16NovoAgendamentoRequest\x12\x11\n\tagenda_id\x18\x01 \x01(\x05\x12\x13\n\x0busuario_cpf\x18\x02 \x01(\t\"P\n\x13\x41gendamentoResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t\x12\x16\n\x0e\x61gendamento_id\x18\x03 \x01(\x05\"\xa0\x01\n\x11\x44\x61shboardResponse\x12\x15\n\rtotal_medicos\x18\x01 \x01(\x05\x12\x17\n\x0ftotal_consultas\x18\x02 \x01(\x05\x12\x16\n\x0e\x63onsultas_hoje\x18\x03 \x01(\x05\x12$\n\x1c\x65specialidade_mais_procurada\x18\x04 \x01(\t\x12\x1d\n\x15medico_mais_procurado\x18\x05 \x01(\t2\xaf\x01\n\x10RelatorioService\x12@\n\x0eGerarDashboard\x12\x10.relatorio.Vazio\x1a\x1c.relatorio.DashboardResponse\x12Y\n\x14RegistrarAgendamento\x12!.relatorio.NovoAgendamentoRequest\x1a\x1e.relatorio.AgendamentoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'relatorio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VAZIO']._serialized_start=30
  _globals['_VAZIO']._serialized_end=37
  _globals['_NOVOAGENDAMENTOREQUEST']._serialized_start=39
  _globals['_NOVOAGENDAMENTOREQUEST']._serialized_end=103
  _globals['_AGENDAMENTORESPONSE']._serialized_start=105
  _globals['_AGENDAMENTORESPONSE']._serialized_end=185
  _globals['_DASHBOARDRESPONSE']._serialized_start=188
  _globals['_DASHBOARDRESPONSE']._serialized_end=348
  _globals['_RELATORIOSERVICE']._serialized_start=351
  _globals['_RELATORIOSERVICE']._serialized_end=526
# @@protoc_insertion_point(module_scope)
