# Generated by Django 6.0.4 on 2026-04-19 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medico_id", models.PositiveIntegerField()),
                ("data", models.DateField()),
                ("horario", models.TimeField()),
                ("disponivel", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario_cpf", models.CharField(max_length=14)),
                (
                    "agenda",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agendamentos.agenda",
                    ),
                ),
            ],
        ),
    ]
